# Generated by Django 5.0.4 on 2024-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
